// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVJJYyp-uhA76e339E9IPJEe6NGKj84w',
    appId: '1:748613645567:web:d589ce332bff7e3bcfc8ca',
    messagingSenderId: '748613645567',
    projectId: 'orcaplus-1309e',
    authDomain: 'orcaplus-1309e.firebaseapp.com',
    storageBucket: 'orcaplus-1309e.firebasestorage.app',
    measurementId: 'G-WZL403F74H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB48W3K0rQAAOWwOKkzYjbHY3Bau_gN0Z8',
    appId: '1:748613645567:android:144fab2715b44ca8cfc8ca',
    messagingSenderId: '748613645567',
    projectId: 'orcaplus-1309e',
    storageBucket: 'orcaplus-1309e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDODHkgIx18GHY8dM9bX54mUO1jAheFYZI',
    appId: '1:748613645567:ios:70bd4e54b2b26fbfcfc8ca',
    messagingSenderId: '748613645567',
    projectId: 'orcaplus-1309e',
    storageBucket: 'orcaplus-1309e.firebasestorage.app',
    iosBundleId: 'br.dev.victorleao.orcafacil',
  );
}
